INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50101010', 'Coal');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50102010', 'Integrated Oil & Gas');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50102020', 'Oil & Gas Exploration and Production');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50102030', 'Oil & Gas Refining and Marketing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50103010', 'Oil & Gas Drilling');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50103020', 'Oil Related Services and Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50103030', 'Oil & Gas Transportation Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50201010', 'Renewable Energy Equipment & Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50201020', 'Renewable Fuels');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('50301010', 'Uranium');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51101010', 'Commodity Chemicals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51101020', 'Agricultural Chemicals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51101030', 'Specialty Chemicals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51101090', 'Diversified Chemicals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201010', 'Precious Metals & Minerals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201020', 'Steel');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201030', 'Aluminum');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201050', 'Specialty Mining & Metals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201060', 'Gold');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201070', 'Mining Support Services & Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51201080', 'Integrated Mining');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51202010', 'Construction Materials');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51301010', 'Forest & Wood Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51301020', 'Paper Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51302010', 'Non-Paper Containers & Packaging');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('51302020', 'Paper Packaging');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52101010', 'Aerospace & Defense');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52102010', 'Industrial Machinery & Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52102020', 'Heavy Machinery & Vehicles');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52102030', 'Electrical Components & Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52102040', 'Heavy Electrical Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52102050', 'Shipbuilding');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52201020', 'Construction & Engineering');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52202010', 'Diversified Trading & Distributing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203010', 'Environmental Services & Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203020', 'Commercial Printing Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203030', 'Employment Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203040', 'Business Support Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203060', 'Business Support Supplies');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52203070', 'Professional Information Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52301010', 'Industrial Conglomerates');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52405010', 'Air Freight & Logistics');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52405020', 'Marine Freight & Logistics');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52405030', 'Ground Freight & Logistics');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52406010', 'Airlines');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52406020', 'Passenger Transportation, Ground & Sea');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52407010', 'Airport Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52407020', 'Marine Port Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('52407030', 'Highways & Rail Tracks');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53101010', 'Auto & Truck Manufacturers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53101020', 'Auto, Truck & Motorcycle Parts');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53101030', 'Tires & Rubber Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53202010', 'Textiles & Leather Goods');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53202020', 'Apparel & Accessories');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53202030', 'Footwear');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53203010', 'Homebuilding');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53203020', 'Construction Supplies & Fixtures');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53204030', 'Appliances, Tools & Housewares');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53204040', 'Home Furnishings');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53205010', 'Toys & Juvenile Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53205020', 'Recreational Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53301010', 'Hotels, Motels & Cruise Lines');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53301020', 'Restaurants & Bars');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53301030', 'Casinos & Gaming');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53301040', 'Leisure & Recreation');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53302010', 'Advertising & Marketing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53302020', 'Broadcasting');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53302030', 'Entertainment Production');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53302040', 'Consumer Publishing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53402010', 'Department Stores');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53402020', 'Discount Stores');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403010', 'Auto Vehicles, Parts & Service Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403020', 'Home Improvement Products & Services Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403030', 'Home Furnishings Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403040', 'Apparel & Accessories Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403050', 'Computer & Electronics Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('53403090', 'Other Specialty Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54101010', 'Brewers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54101020', 'Distillers & Wineries');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54101030', 'Non-Alcoholic Beverages');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54102010', 'Fishing & Farming');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54102020', 'Food Processing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54102030', 'Tobacco');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54201010', 'Household Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54201020', 'Personal Products');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54201030', 'Personal Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54301010', 'Drug Retailers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('54301020', 'Food Retail & Distribution');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55101010', 'Banks');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55101030', 'Consumer Lending');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55101050', 'Corporate Financial Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55102010', 'Investment Banking & Brokerage Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55102020', 'Investment Management & Fund Operators');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55102030', 'Diversified Investment Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55102050', 'Financial & Commodity Market Operators');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55301010', 'Multiline Insurance & Brokers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55301020', 'Property & Casualty Insurance');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55301030', 'Life & Health Insurance');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55301050', 'Reinsurance');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55402010', 'Real Estate Development & Operations');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55402020', 'Real Estate Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55403010', 'Diversified REITs');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55403020', 'Commercial REITs');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55403030', 'Residential REITs');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55403040', 'Specialized REITs');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501010', 'Investment Trusts');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501020', 'Mutual Funds');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501030', 'Closed End Funds');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501040', 'Exchange Traded Funds');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501050', 'Pension Funds');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55501060', 'Insurance Funds');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('55601010', 'Holding Companies');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56101010', 'Advanced Medical Equipment & Technology');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56101020', 'Medical Equipment, Supplies & Distribution');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56102010', 'Healthcare Facilities & Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56102020', 'Managed Healthcare');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56201040', 'Pharmaceuticals');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('56202010', 'Biotechnology & Medical Research');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57101010', 'Semiconductors');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57101020', 'Semiconductor Equipment & Testing');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57102010', 'Communications & Networking');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57104010', 'Electronic Equipment & Parts');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57105010', 'Office Equipment');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57106010', 'Computer Hardware');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57106020', 'Phones & Handheld Devices');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57106030', 'Household Electronics');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57201010', 'IT Services & Consulting');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57201020', 'Software');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('57201030', 'Internet Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('58101010', 'Integrated Telecommunications Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('58101020', 'Wireless Telecommunications Services');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('59101010', 'Electric Utilities');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('59101020', 'Independent Power Producers');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('59102010', 'Natural Gas Utilities');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('59103010', 'Water Utilities');
INSERT INTO industrysectors (parmcode, sectordesc) VALUES ('59104010', 'Multiline Utilities');
