INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010001, 'FIX-RATE-BOND', 'Fixed Rate Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010002, 'FLT-RATE-BOND', 'Floating Rate Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010003, 'ZC-BOND', 'Zero Coupon Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010004, 'PP-BOND', 'Perpetual Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010005, 'MUNICIPAL', 'Municipal Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010006, 'CONVT-BOND', 'Convertible Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010008, 'INFLATION-BOND', 'Index/Inflation Linked Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010010, 'T-BOND', 'Treasury Bond');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010015, 'TERM-NOTE', 'Term Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010016, 'ACCR-NOTE', 'Accrual Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010099, 'BOND-GEN', 'Bond - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010301, 'Z_TERM-NOTE', 'Generic Term Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11010303, 'Z_ACCR-NOTE', 'Generic Accrual Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030001, 'SHARES', 'Share');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030002, 'PREFER-SHARES', 'Preferred Share');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030003, 'CONVT-SHARES', 'Convertible Share');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030031, 'ETF', 'Exchange-Traded Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030051, 'EQUITY-WRNT', 'Equity Warrant');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (11030099, 'EQUITY-GEN', 'Equity - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13010001, 'FXSP', 'FX Spot');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050001, 'TERM-DEPO', 'Term Deposit');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050002, 'CALL-DEPO', 'Call Deposit');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050003, 'FD-DEPO', 'Fiduciary Deposit');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050005, 'CD', 'Certificate of Deposit');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050006, 'CP', 'Commercial Paper');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050099, 'DEPO-GEN', 'Deposit - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050101, 'TERM-LOAN', 'Term Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050102, 'CALL-LOAN', 'Call Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050103, 'FD-LOAN', 'Fiduciary Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050199, 'LOAN-GEN', 'Loan - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050399, 'MM-GEN', 'Money Market - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010001, 'CMD-MT', 'Metal');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010031, 'CMD-EG', 'Energy');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010061, 'CMD-AR', 'Agriculture');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010081, 'CMD-LS', 'Livestock');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010099, 'CMD-GEN', 'Commodity - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510001, 'EQT-IDX', 'Equity Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510003, 'BOND-IDX', 'Bond Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510005, 'FUND-IDX', 'Fund Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510010, 'IR-IDX', 'Interest Rate Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510099, 'IDX-GEN', 'Index - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010001, 'UNIT-TRUST', 'Unit Trust');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010003, 'MUTUAL-FUND', 'Mutual Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010020, 'BOND-FUND', 'Bond Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050005, 'CD', 'Certificate of Deposit');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050006, 'CP', 'Commercial Paper');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050099, 'DEPO-GEN', 'Deposit - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050101, 'TERM-LOAN', 'Term Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050102, 'CALL-LOAN', 'Call Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050103, 'FD-LOAN', 'Fiduciary Loan');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050199, 'LOAN-GEN', 'Loan - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (13050399, 'MM-GEN', 'Money Market - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010001, 'CMD-MT', 'Metal');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010031, 'CMD-EG', 'Energy');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010061, 'CMD-AR', 'Agriculture');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010081, 'CMD-LS', 'Livestock');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17010099, 'CMD-GEN', 'Commodity - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510001, 'EQT-IDX', 'Equity Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510003, 'BOND-IDX', 'Bond Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510005, 'FUND-IDX', 'Fund Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510010, 'IR-IDX', 'Interest Rate Index');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (17510099, 'IDX-GEN', 'Index - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010001, 'UNIT-TRUST', 'Unit Trust');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010003, 'MUTUAL-FUND', 'Mutual Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010020, 'BOND-FUND', 'Bond Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010025, 'REAL-EST-FUND', 'Real Estate Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010035, 'MM-FUND', 'Money Market Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010040, 'DIGITAL-FUND', 'Digital Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010050, 'FOF', 'Fund of Funds');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18010099, 'FUND-GEN', 'Fund - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18030001, 'HEDGE-FUND', 'Hedge Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18210001, 'PE-GEN', 'Private Equity - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18210005, 'PE-FUND', 'Private Equity Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18210008, 'PE-FIN-FUND', 'Private Equity Finance Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18210010, 'PE-REAL-EST-FUND', 'Private Equity Real Estate Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18210015, 'VC-FUND', 'Venture Capital Fund');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18310099, 'INSUR-GEN', 'Insurance - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18510099, 'INVT-PORTF', 'Investment Portfolio');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (18510199, 'COLLECT-INVT-GEN', 'Collective Investment - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (19010099, 'DIGITAL-ASSET-GEN', 'Digital Asset - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010001, 'ELN', 'Equity Linked Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010002, 'KOELN', 'Knock-out Equity Linked Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010003, 'FCN', 'Fixed Coupon Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010004, 'DRAN', 'Daily Range Accrual Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010005, 'DDK', 'Double Decker');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010006, 'ERCN', 'Equity Reverse Convertible Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010007, 'ERCN-KI', 'Equity Reverse Convertible Note - KI');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010008, 'CRAN', 'Callable Range Accrual Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010009, 'EMACFCN', 'Equity Memory Autocallable Fixed Coupon Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010020, 'DISCRT', 'Discount Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010021, 'EDIGIN-KI', 'Equity Digital Coupon Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010022, 'EBSTRN', 'Equity Booster Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010023, 'EPHXCN-KI', 'Equity Phoenix Callable Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010024, 'ESDACN', 'Equity Stepdown Autocallable Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010025, 'ESDACN-KI', 'Equity Stepdown Autocallable Note - KI');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010026, 'ELC', 'Equity Leveraged Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010027, 'ETC', 'Equity Tracker Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010028, 'ETW', 'Equity Twin Win');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010030, 'DAC', 'Equity Accumulator / Decumulator');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010051, 'EBEN', 'Equity Bonus Enhanced Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010060, 'BLC', 'Bond Leveraged Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010061, 'BTC', 'Bond Tracker Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010080, 'AMC', 'Actively Managed Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010085, 'FLN', 'Fund Linked Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010086, 'FLN-KI', 'Fund Linked Note - KI');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010088, 'FLC', 'Fund Leveraged Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010090, 'FTC', 'Fund Tracker Certificate');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (510100A1, 'CSDACN', 'Commodity Stepdown Autocallable Note');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (510100A2, 'CSDACN-KI', 'Commodity Stepdown Autocallable Note - KI');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (510100A3, 'OTW', 'Oil Twin Win');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010100, 'SN', 'Structured Note - General');
INSERT INTO assettypes (assetid, assetshort, assetdesc) VALUES (51010111, 'SP-CAPPRO-GEN', 'Structured Product Capital Protection - General');
