INSERT INTO regions (regionid, regionname) VALUES (1, 'Africa');
INSERT INTO regions (regionid, regionname) VALUES (2, 'Americas');
INSERT INTO regions (regionid, regionname) VALUES (3, 'Antarctica');
INSERT INTO regions (regionid, regionname) VALUES (4, 'Asia');
INSERT INTO regions (regionid, regionname) VALUES (5, 'Asia ex-Japan');
INSERT INTO regions (regionid, regionname) VALUES (6, 'BRIC');
INSERT INTO regions (regionid, regionname) VALUES (7, 'Carribbean');
INSERT INTO regions (regionid, regionname) VALUES (8, 'Central Africa');
INSERT INTO regions (regionid, regionname) VALUES (9, 'Central America');
INSERT INTO regions (regionid, regionname) VALUES (10, 'Central Asia');
INSERT INTO regions (regionid, regionname) VALUES (11, 'Central Europe');
INSERT INTO regions (regionid, regionname) VALUES (12, 'EAFE');
INSERT INTO regions (regionid, regionname) VALUES (13, 'Eastern Africa');
INSERT INTO regions (regionid, regionname) VALUES (14, 'Eastern Asia');
INSERT INTO regions (regionid, regionname) VALUES (15, 'Eastern Europe');
INSERT INTO regions (regionid, regionname) VALUES (16, 'Emerging Markets (EM) Asia');
INSERT INTO regions (regionid, regionname) VALUES (17, 'Emerging Markets (EM) Europe');
INSERT INTO regions (regionid, regionname) VALUES (18, 'Europe');
INSERT INTO regions (regionid, regionname) VALUES (19, 'European Union');
INSERT INTO regions (regionid, regionname) VALUES (20, 'Middle East');
INSERT INTO regions (regionid, regionname) VALUES (21, 'NAFTA');
INSERT INTO regions (regionid, regionname) VALUES (22, 'North America');
INSERT INTO regions (regionid, regionname) VALUES (23, 'Northern Africa');
INSERT INTO regions (regionid, regionname) VALUES (24, 'Northern Europe');
INSERT INTO regions (regionid, regionname) VALUES (25, 'Oceania');
INSERT INTO regions (regionid, regionname) VALUES (26, 'South America');
INSERT INTO regions (regionid, regionname) VALUES (27, 'South-Eastern Asia');
INSERT INTO regions (regionid, regionname) VALUES (28, 'Southern Africa');
INSERT INTO regions (regionid, regionname) VALUES (29, 'Southern Asia');
INSERT INTO regions (regionid, regionname) VALUES (30, 'Southern Europe');
INSERT INTO regions (regionid, regionname) VALUES (31, 'Western Africa');
INSERT INTO regions (regionid, regionname) VALUES (32, 'Western Europe');
