INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AFG', 'Afganistan', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ALA', 'Aland Islands', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ALB', 'Albania', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DZA', 'Algeria', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ASM', 'American Samoa', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AND', 'Andorra', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AGO', 'Angola', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AIA', 'Anguilla', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ATA', 'Antarctica', 3);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ATG', 'Antigua and Barbuda', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ARG', 'Argentina', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ARM', 'Armenia', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ABW', 'Aruba', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AUS', 'Australia', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AUT', 'Austria', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('AZE', 'Azerbaijan', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BHS', 'Bahamas', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BHR', 'Bahrain', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BGD', 'Bangladesh', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BRB', 'Barbados', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BLR', 'Belarus', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BEL', 'Belgium', 32);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BLZ', 'Belize', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BEN', 'Benin', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BMU', 'Bermuda', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BTN', 'Bhutan', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BOL', 'Bolivia', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BES', 'Bonaire,  Saint Eustatius and Saba', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BIH', 'Bosnia and Herzegovina', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BWA', 'Botswana', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BRA', 'Brazil', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IOT', 'British Indian Ocean Territory', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BRN', 'Brunei Darussalam', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BGR', 'Bulgaria', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BFA', 'Burkina Faso', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BDI', 'Burundi', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CPV', 'Cabo Verde', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KHM', 'Cambodia', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CMR', 'Cameroon', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CAN', 'Canada', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CYM', 'Cayman Islands', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CAF', 'Central African Republic', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TCD', 'Chad', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CHL', 'Chile', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CHN', 'China', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CXR', 'Christmas Island', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CCK', 'Cocos Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('COL', 'Colombia', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('COM', 'Comoros', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('COG', 'Congo', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('COD', 'Congo, Democratic Republic of the', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('COK', 'Cook Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CRI', 'Costa Rica', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CIV', 'Ivory Coast', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('HRV', 'Croatia', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CUB', 'Cuba', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CUW', 'Curaçao', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CYP', 'Cyprus', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CZE', 'Czech Republic', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DNK', 'Denmark', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DJI', 'Djibouti', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DMA', 'Dominica', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DOM', 'Dominican Republic', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ECU', 'Ecuador', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('EGY', 'Egypt', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SLV', 'El Salvador', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GNQ', 'Equatorial Guinea', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ERI', 'Eritrea', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('EST', 'Estonia', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ETH', 'Ethiopia', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FLK', 'Falkland Islands (Malvinas)', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FRO', 'Faroe Islands', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FJI', 'Fiji', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FIN', 'Finland', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FRA', 'France', 32);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GUF', 'French Guiana', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PYF', 'French Polynesia', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GAB', 'Gabon', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GMB', 'Gambia', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GEO', 'Georgia', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('DEU', 'Germany', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GHA', 'Ghana', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GIB', 'Gibraltar', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GRC', 'Greece', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GRL', 'Greenland', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GRD', 'Grenada', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GLP', 'Guadeloupe', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GUM', 'Guam', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GTM', 'Guatemala',9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GGY', 'Guersney', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GIN', 'Guinea', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GNB', 'Guinea-Bissau', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GUY', 'Guyana', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('HTI', 'Haiti', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('HND', 'Honduras', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('HKG', 'Hong Kong', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('HUN', 'Hungary', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ISL', 'Iceland', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IND', 'India', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IDN', 'Indonesia', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IRN', 'Iran', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IRQ', 'Iraq', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IRL', 'Ireland', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('IMN', 'Isle of Man', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ISR', 'Israel', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ITA', 'Italy', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('JAM', 'Jamaica', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('JPN', 'Japan', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('JEY', 'Jersey', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('JOR', 'Jordan', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KAZ', 'Kazakhstan', 10);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KEN', 'Kenya', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KIR', 'Kiribati', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KWT', 'Kuwait', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KGZ', 'Kyrgyzstan', 10);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LAO', 'Lao', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LVA', 'Latvia', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LBN', 'Lebanon', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LSO', 'Lesotho', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LBR', 'Liberia', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LBY', 'Libya', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LIE', 'Liechtenstein', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LTU', 'Lithuania', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LUX', 'Luxembourg', 32);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MAC', 'Macao', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MKD', 'Macedonia', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MDG', 'Madagascar', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MWI', 'Malawi', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MYS', 'Malaysia', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MDV', 'Maldives', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MLI', 'Mali', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MLT', 'Malta', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MHL', 'Marshall Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MTQ', 'Martinique', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MRT', 'Mauritania', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MUS', 'Mauritius', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MYT', 'Mayotte', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MEX', 'Mexico', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('FSM', 'Micronesia', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MDA', 'Moldova', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MCO', 'Monaco', 32);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MNG', 'Mongolia', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MNE', 'Montenegro', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MSR', 'Montserrat', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MAR', 'Morroco', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MOZ', 'Mozambique', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MMR', 'Myanmar', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NAM', 'Namibia', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NRU', 'Nauru', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NPL', 'Nepal', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NLD', 'Netherlands', 32);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NCL', 'New Caledonia', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NZL', 'New Zealand', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NIC', 'Nicaragua', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NER', 'Niger', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NGA', 'Nigeria', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NIU', 'Niue', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NFK', 'Norfolk Island', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PRK', 'North Korea', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MNP', 'Northern Mariana Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('NOR', 'Norway', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('OMN', 'Oman', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PAK', 'Pakistan', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PLW', 'Palau', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PSE', 'Palestine', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PAN', 'Panama', 9);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PNG', 'Papua New Guinea', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PRY', 'Paraguay', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PER', 'Peru', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PHL', 'Philippines', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PCN', 'Pitcairn Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('POL', 'Poland', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PRT', 'Portugal', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('PRI', 'Puerto Rico', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('QAT', 'Qatar', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('REU', 'Reunion', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ROU', 'Romania', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('RUS', 'Russian Federation', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('RWA', 'Rwanda', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SHN', 'Saint Helena', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LCA', 'Saint Lucia', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('MAF', 'Saint Martin', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SPM', 'Saint Pierre and Miquelon', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VCT', 'Saint Vincent and the Grenadines', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('BLM', 'Saint-Barthélemy', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('WSM', 'Samoa', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SMR', 'San Marino', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('STP', 'Sao Tome and Principe', 8);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SAU', 'Saudi Arabia', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SEN', 'Senegal', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SRB', 'Serbia', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SYC', 'Seychelles', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SLE', 'Sierra Leone', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SGP', 'Singapore', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SXM', 'Sint Maarten (Dutch part)', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SVK', 'Slovakia', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SVN', 'Slovenia', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SLB', 'Solomon Islands', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SOM', 'Somalia', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ZAF', 'South Africa', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SGS', 'South Georgia and the South Sandwich Islands', 3);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KOR', 'South Korea', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SSD', 'South Sudan', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ESP', 'Spain', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('LKA', 'Sri Lanka', 29);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('KNA', 'St. Kitts and Nevis', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SDN', 'Sudan', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SUR', 'Suriname', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SJM', 'Svalbard and Jan Mayen', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SWZ', 'Swaziland (Eswatini)', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SWE', 'Sweden', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('CHE', 'Switzerland', 11);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('SYR', 'Syrian Arab Republic', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TWN', 'Taiwan', 14);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TJK', 'Tajikistan', 10);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TZA', 'Tanzania', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('THA', 'Thailand', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TLS', 'Timor-Leste', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TGO', 'Togo', 31);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TKL', 'Tokelau', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TON', 'Tonga', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TTO', 'Trinidad and Tobago', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TUN', 'Tunisia', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TUR', 'Turkey', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TKM', 'Turkmenistan', 10);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TCA', 'Turks and Caicos Islands', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('TUV', 'Tuvalu', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('UGA', 'Uganda', 13);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('UKR', 'Ukraine', 15);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ARE', 'United Arab Emirates', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('GBR', 'United Kingdom', 24);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('UMI', 'United States Minor Outlying Islands', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('USA', 'United States of America', 22);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('URY', 'Uruguay', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('UZB', 'Uzbekistan', 10);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VUT', 'Vanuatu', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VAT', 'Vatican City', 30);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VEN', 'Venezuela', 26);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VNM', 'Vietnam', 27);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VGB', 'Virgin Islands (British)', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('VIR', 'Virgin Islands (US)', 7);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('WLF', 'Wallis and Futuna', 25);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ESH', 'Western Sahara', 23);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('YEM', 'Yemen', 20);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ZMB', 'Zambia', 28);
INSERT INTO countries (countrycode, countryname, regionid) VALUES ('ZWE', 'Zimbabwe', 28);